parameters:
    kaku.ssh.configuration.class: Ssh\Configuration
    kaku.ssh.publickeyfile.class: Ssh\Authentication\PublicKeyFile
    kaku.ssh.session.class: Ssh\Session
    kaku.command.class: Kaku\Command\SshCommand
    kaku.switcher.class: Kaku\Switcher

services:
    kaku.ssh.configuration:
        class: %kaku.ssh.configuration.class%
        arguments: [ %kaku.ssh.host% ]

    kaku.ssh.authentication:
        class: %kaku.ssh.publickeyfile.class%
        arguments:
            - %kaku.ssh.username%
            - %kaku.ssh.public_key%
            - %kaku.ssh.private_key%
            - ''

    kaku.ssh.session:
        class: %kaku.ssh.session.class%
        arguments: [ @kaku.ssh.configuration, @kaku.ssh.authentication ]

    kaku.kaku.command:
        class: %kaku.command.class%
        arguments:
            - @kaku.ssh.session
            - %kaku.command%

    kaku.kaku.switcher:
        class: %kaku.switcher.class%
        arguments:
            - @kaku.kaku.command
